import type { Metadata } from "next";
import { ADLaM_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const cmforter = ADLaM_Display({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cmforter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
